### PR TITLE
Fix for Travis Deployment issue

### PR DESCRIPTION
**Pull request by dresrok**
For some reason there was an error installing node-sass. It looks like a bug between yarn and this package. I updated  it to the latest version and it works.

### CODE REVIEW

**Comment by Diegoavilap** [comment]
How could I check that it will work fine when we deploy it? @Gioyik

**Comment by Gioyik** [comment]
There's clearly an issue here with the commits. You have the same changes under two different commits.

`6f46047` in this PR, `d1cc57b2` in dev branch. Please, fix it.

**Comment by Gioyik** [comment]
ok, a few things to consider when upgrading node-sass:

First, check the release support and which version of node are you supposed to use with each release:

* Supported Node.js versions vary by release, please consult the [releases page](https://github.com/sass/node-sass/releases). Below is a quick guide for minimium support:

NodeJS  | Minimum node-sass version | Node Module
--------|--------------------------|------------
Node 12 | 4.12+                    | 72
Node 11 | 4.10+                    | 67
Node 10 | 4.9+                     | 64
Node 8  | 4.5.3+                   | 57

From the travis logs I can confirm:

```
$ node --version
v12.1.0
$ npm --version
6.9.0
$ nvm --version
0.34.0
$ yarn --version
1.3.2
````

So, seems we are fine upgrading to `4.12.x`, however I am not if that has side effects, hopefully not.  This is what i think could be happening: https://semver.npmjs.com

Somehow `yarn` in Travis is ignoring the lock file and creating it's own cache, and because we are using `^` for the version, that means it can update to whatever new version is available after `4.9.x`, that's the one we had. If we want to freeze deps, we need to make sure the lock file is working as expected with Travis or avoid using `^` and setting specific versioning.

You can check how `^` and `~` is implied in the package.json and which range or versions to expect be available using those.

@Diegoavilap just run `yarn install`, that should pass, and probably bahaves the same on the CI, but most likely requires attention to the lock file or the cache in Travis.

**Review by Gioyik — CHANGES_REQUESTED** [review]
Check the comments I left, ping me if I was not clear.

**Comment by Gioyik** [comment]
is probably something for later, but seems we should have Travis run in PR to avoid this type of things, but without deploying. If someone has ideas :)

**Pull request closed without merging**
